import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Container from "@/components/Container";
import ChatBot from "@/components/ChatBot";
import AnalyticsTracker from "./AnaliyticsTracker";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Shah Emdadia Freelancers'",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  data-theme="light">
       <head>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-K0ZT9GH5N9"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-K0ZT9GH5N9');
          `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
         
        {/* <Navbar/>
        <div className="fixed bottom-12 right-12 hover:cursor-pointer">
          <ChatBot/>
        </div> */}

        <div className="">

          {children}

        </div>
        {/* <div className="bg-[#FDF4EC] background">
          
            {children}
    
        </div> */}
        <AnalyticsTracker />
      </body>
    </html>
  );
}
