import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

import ChatBot from "@/components/ChatBot";
import AnalyticsTracker from "./AnaliyticsTracker";
import Script from "next/script";
import SocialIcons from "@/components/SocialIcon";
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Shah Emdadia Freelancers'",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=G-${process.env.NEXT_PUBLIC_GoogleAnalitics_GID}`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-${process.env.NEXT_PUBLIC_GoogleAnalitics_GID}');
          `}
        </Script>
      </head>
      <body
        style={{
          backgroundImage: "url('/asset/background.png')",
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
          backgroundAttachment: "fixed",
          height: "100vh",
          width: "100%",
        }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-white`}
      >
        <div className="bg-white/50">
          <Navbar />
          <div className="fixed bottom-12 right-12 hover:cursor-pointer z-50">
            <ChatBot />
          </div>
          <div className="fixed bottom-1/2 left-12 translate-y-1/2 hover:cursor-pointer z-50">
            <SocialIcons className={"flex-col gap-y-4 text-[#00280b]"} />
          </div>

          <div className="">{children}</div>
          <Footer />
          {/* <div className="bg-[#FDF4EC] background">{children}</div> */}
          <AnalyticsTracker />
        </div>
      </body>
    </html>
  );
}
