import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Container from "@/components/Container";
import ChatBot from "@/components/ChatBot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Shah Emdadia Freelancers'",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar/>
        <div className="fixed bottom-12 right-12 hover:cursor-pointer">
          <ChatBot/>
        </div> */}

        <div className="">
          
            {children}
    
        </div>
        {/* <div className="bg-[#FDF4EC] background">
          
            {children}
    
        </div> */}
      </body>
    </html>
  );
}
